# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Website Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  website_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SvelteKit on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ github.event.pull_request.number }}-

      - name: Install Dependencies
        run: npm ci

      - name: Copy .env from .env.example
        run: cp .env.example .env

      # checks for lint errors AND format errors
      - name: Lint
        run: npm run lint && git diff --exit-code

      - name: Check
        run: npm run check

      - name: npx playwright install
        run: npx playwright install

      - name: Test
        run: npm t

      # info: https://etok.codes/acmcsuf.com/blob/main/CONTRIBUTING.md#npm-bloat
      - name: Test Dependency Size
        run: npm run test:size
