name: Update Officer Data

on:
  issues:
    types: [opened, reopened]

jobs:
  update_officer:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'automation:officer') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Issue Form
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - run: node scripts/update-officer.js
        env:
          FORM_DATA: ${{ steps.parse.outputs.payload }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updated officer data
          title: '[OFFICER_AUTOMATION]'
          body: These changes resolve officer update request \#${{ github.event.issue.number }} âœ¨

      - name: Close Issue
        id: close_successfully
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Closed by \#${{ steps.pull_request.outputs.pull-request-number }} âœ¨
